# Generated by Django 6.0.1 on 2026-02-05 18:27

import easy_thumbnails.fields
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text='Выберите область для отображения аватара', hide_image_field=False, size_warning=True, verbose_name='Область кадрирования'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='ИЛИ вставьте ссылку на изображение', max_length=500, verbose_name='Аватар (по ссылке)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
