# Generated by Django 6.0.1 on 2026-02-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_avatar_cropping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_cropping',
        ),
    ]
