# Generated by Django 6.0.1 on 2026-02-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_avatar_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_cropping',
            field=models.CharField(blank=True, help_text='JSON с координатами кадрирования', max_length=100, verbose_name='Данные кадрирования'),
        ),
    ]
