# Generated by Django 5.2.12 on 2026-04-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Персонал клуба'), ('active', 'Активный читатель'), ('guest', 'Гость')], default='active', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
