# Generated by Django 5.2.12 on 2026-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_clubevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='target_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
