# Generated by Django 5.2.12 on 2026-04-27 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_clubevent_target_id_clubevent_target_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubevent',
            name='is_read',
        ),
        migrations.AddField(
            model_name='clubevent',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
