# Generated by Django 5.2.12 on 2026-06-09 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_clubevent_is_read_clubevent_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubevent',
            name='target_url',
        ),
        migrations.AddField(
            model_name='clubevent',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='event_type',
            field=models.CharField(choices=[('user_registered', 'Новый участник'), ('book_added', 'Добавлена книга'), ('review_written', 'Написана рецензия'), ('book_favorited', 'Книга добавлена в избранное'), ('rating_given', 'Поставил оценку книге'), ('review_liked', 'Оценил рецензию'), ('review_disliked', 'Отметил рецензию')], max_length=50),
        ),
    ]
