# Generated by Django 6.0.1 on 2026-02-05 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('review', models.TextField(blank=True, verbose_name='Рецензия пользователя')),
                ('genre', models.CharField(blank=True, choices=[('fantasy', 'Фантастика'), ('detective', 'Детектив'), ('romance', 'Роман'), ('historical', 'Исторический'), ('horror', 'Ужасы'), ('scifi', 'Научная фантастика'), ('adventure', 'Приключения'), ('biography', 'Биография'), ('classic', 'Классика'), ('modern', 'Современная проза'), ('poetry', 'Поэзия'), ('drama', 'Драма'), ('comedy', 'Комедия'), ('thriller', 'Триллер'), ('mystery', 'Мистика'), ('children', 'Детская литература'), ('nonfiction', 'Нон-фикшн'), ('other', 'Другое')], max_length=50, verbose_name='Жанр')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/submissions/', verbose_name='Обложка')),
                ('cover_url', models.URLField(blank=True, verbose_name='Ссылка на обложку')),
                ('plot_rating', models.IntegerField(default=0, verbose_name='Сюжет (0-10)')),
                ('characters_rating', models.IntegerField(default=0, verbose_name='Персонажи (0-10)')),
                ('style_rating', models.IntegerField(default=0, verbose_name='Стиль (0-10)')),
                ('originality_rating', models.IntegerField(default=0, verbose_name='Оригинальность (0-10)')),
                ('impression_rating', models.IntegerField(default=0, verbose_name='Впечатление (0-10)')),
                ('want_rating', models.BooleanField(default=False, verbose_name='Хочу оценить')),
                ('is_favorite', models.BooleanField(default=False, help_text='Пользователь отметил как любимую (видно админу)', verbose_name='Любимая книга пользователя')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата предложки')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Предложил')),
            ],
            options={
                'verbose_name': 'Предложка книги',
                'verbose_name_plural': 'Предложки книг',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('genre', models.CharField(blank=True, default='other', max_length=200, verbose_name='Жанры')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/top/', verbose_name='Обложка')),
                ('cover_url', models.URLField(blank=True, verbose_name='Ссылка на обложку')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать в ТОПе')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в ТОП')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_in_top', to='books.booksubmission', verbose_name='Исходная предложка')),
            ],
            options={
                'verbose_name': 'Книга в ТОПе',
                'verbose_name_plural': 'Книги в ТОПе',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Почему добавил в избранное', verbose_name='Заметка пользователя')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_books', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранная книга',
                'verbose_name_plural': 'Избранные книги',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_depth', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, verbose_name='Прописанность персонажей')),
                ('idea_reveal', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, verbose_name='Раскрытие авторской идеи')),
                ('readability', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, verbose_name='Читаемость')),
                ('relevance', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, verbose_name='Актуальность')),
                ('overall_impression', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, verbose_name='Общее впечатление')),
                ('comment', models.TextField(blank=True, verbose_name='Рецензия пользователя')),
                ('is_from_submission', models.BooleanField(default=False, verbose_name='Рецензия из предложки')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Редактировалась')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка книги',
                'verbose_name_plural': 'Оценки книг',
                'ordering': ['-created_at'],
                'unique_together': {('book', 'user')},
            },
        ),
    ]
