# Generated by Django 6.0.1 on 2026-02-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fantasy', 'Фантастика'), ('detective', 'Детектив'), ('romance', 'Роман'), ('historical', 'Исторический'), ('horror', 'Ужасы'), ('scifi', 'Научная фантастика'), ('adventure', 'Приключения'), ('biography', 'Биография'), ('classic', 'Классика'), ('modern', 'Современная проза'), ('poetry', 'Поэзия'), ('drama', 'Драма'), ('comedy', 'Комедия'), ('thriller', 'Триллер'), ('mystery', 'Мистика'), ('children', 'Детская литература'), ('nonfiction', 'Нон-фикшн'), ('other', 'Другое')], max_length=50, null=True),
        ),
    ]
