# Generated by Django 6.0.1 on 2026-02-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_genre_alter_booksubmission_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Художественная литература'), ('classic', 'Классика'), ('fantasy', 'Фэнтези'), ('scifi', 'Научная фантастика'), ('detective', 'Детектив'), ('thriller', 'Триллер'), ('romance', 'Любовный роман'), ('short_story', 'Рассказ'), ('novella', 'Повесть'), ('historical', 'Исторический'), ('adventure', 'Приключения'), ('horror', 'Ужасы'), ('mystery', 'Мистика'), ('drama', 'Драма'), ('comedy', 'Комедия'), ('biography', 'Биография'), ('philosophy', 'Философия'), ('psychology', 'Психология'), ('history', 'История'), ('science', 'Наука'), ('popular_science', 'Научно-популярная литература'), ('nonfiction', 'Нон-фикшн'), ('poetry', 'Поэзия'), ('children', 'Детская'), ('young_adult', 'Для подростков'), ('self_help', 'Саморазвитие'), ('comic', 'Комикс'), ('manga', 'Манга'), ('fanfiction', 'Фанфик'), ('erotica', 'Эротика'), ('other', 'Другое')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booksubmission',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Художественная литература'), ('classic', 'Классика'), ('fantasy', 'Фэнтези'), ('scifi', 'Научная фантастика'), ('detective', 'Детектив'), ('thriller', 'Триллер'), ('romance', 'Любовный роман'), ('short_story', 'Рассказ'), ('novella', 'Повесть'), ('historical', 'Исторический'), ('adventure', 'Приключения'), ('horror', 'Ужасы'), ('mystery', 'Мистика'), ('drama', 'Драма'), ('comedy', 'Комедия'), ('biography', 'Биография'), ('philosophy', 'Философия'), ('psychology', 'Психология'), ('history', 'История'), ('science', 'Наука'), ('popular_science', 'Научно-популярная литература'), ('nonfiction', 'Нон-фикшн'), ('poetry', 'Поэзия'), ('children', 'Детская'), ('young_adult', 'Для подростков'), ('self_help', 'Саморазвитие'), ('comic', 'Комикс'), ('manga', 'Манга'), ('fanfiction', 'Фанфик'), ('erotica', 'Эротика'), ('other', 'Другое')], max_length=50, verbose_name='Жанр'),
        ),
    ]
