# Generated by Django 6.0.1 on 2026-02-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_genre_alter_booksubmission_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='character_depth',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=None, null=True, verbose_name='Прописанность персонажей'),
        ),
        migrations.AlterField(
            model_name='review',
            name='idea_reveal',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=None, null=True, verbose_name='Раскрытие авторской идеи'),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_impression',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=None, null=True, verbose_name='Общее впечатление'),
        ),
        migrations.AlterField(
            model_name='review',
            name='readability',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=None, null=True, verbose_name='Читаемость'),
        ),
        migrations.AlterField(
            model_name='review',
            name='relevance',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=None, null=True, verbose_name='Актуальность'),
        ),
    ]
