# Generated by Django 5.2.12 on 2026-03-09 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_review_options_alter_book_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_club_book',
            field=models.BooleanField(default=False, verbose_name='Книга отмечена клубом'),
        ),
        migrations.AddField(
            model_name='booksubmission',
            name='is_club_book',
            field=models.BooleanField(default=False, verbose_name='Книга отмечена клубом'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Художественная литература'), ('classic', 'Классика'), ('fantasy', 'Фэнтези'), ('scifi', 'Научная фантастика'), ('detective', 'Детектив'), ('thriller', 'Триллер'), ('romance', 'Любовный роман'), ('short_story', 'Рассказ'), ('novella', 'Повесть'), ('historical', 'Исторический'), ('adventure', 'Приключения'), ('horror', 'Ужасы'), ('mystery', 'Мистика'), ('drama', 'Драма'), ('comedy', 'Комедия'), ('biography', 'Биография'), ('philosophy', 'Философия'), ('psychology', 'Психология'), ('history', 'История'), ('science', 'Наука'), ('popular_science', 'Научно-популярная литература'), ('nonfiction', 'Нон-фикшн'), ('poetry', 'Поэзия'), ('children', 'Детская'), ('young_adult', 'Для подростков'), ('self_help', 'Саморазвитие'), ('comic', 'Комикс'), ('manga', 'Манга'), ('fanfiction', 'Фанфик'), ('erotica', 'Эротика'), ('novel', 'Роман'), ('other', 'Другое')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booksubmission',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Художественная литература'), ('classic', 'Классика'), ('fantasy', 'Фэнтези'), ('scifi', 'Научная фантастика'), ('detective', 'Детектив'), ('thriller', 'Триллер'), ('romance', 'Любовный роман'), ('short_story', 'Рассказ'), ('novella', 'Повесть'), ('historical', 'Исторический'), ('adventure', 'Приключения'), ('horror', 'Ужасы'), ('mystery', 'Мистика'), ('drama', 'Драма'), ('comedy', 'Комедия'), ('biography', 'Биография'), ('philosophy', 'Философия'), ('psychology', 'Психология'), ('history', 'История'), ('science', 'Наука'), ('popular_science', 'Научно-популярная литература'), ('nonfiction', 'Нон-фикшн'), ('poetry', 'Поэзия'), ('children', 'Детская'), ('young_adult', 'Для подростков'), ('self_help', 'Саморазвитие'), ('comic', 'Комикс'), ('manga', 'Манга'), ('fanfiction', 'Фанфик'), ('erotica', 'Эротика'), ('novel', 'Роман'), ('other', 'Другое')], max_length=50, verbose_name='Жанр'),
        ),
        migrations.CreateModel(
            name='BookClubStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('club', '📖 Клубные'), ('non_club', '📕 Не клубные'), ('common', '📚 Общие')], default='common', max_length=20, verbose_name='Статус в клубе')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_status', to='books.book', verbose_name='Книга')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Последний изменивший')),
            ],
            options={
                'verbose_name': 'Статус книги в клубе',
                'verbose_name_plural': 'Статусы книг в клубе',
            },
        ),
    ]
