# Generated by Django 5.2.12 on 2026-03-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_is_club_book_booksubmission_is_club_book_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookClubStatus',
        ),
    ]
