# Generated by Django 5.2.12 on 2026-04-02 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_delete_bookclubstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Художественная литература'), ('classic', 'Классика'), ('fantasy', 'Фэнтези'), ('dystopia', 'Антиутопия'), ('scifi', 'Научная фантастика'), ('detective', 'Детектив'), ('thriller', 'Триллер'), ('romance', 'Любовный роман'), ('short_story', 'Рассказ'), ('novella', 'Повесть'), ('historical', 'Исторический'), ('adventure', 'Приключения'), ('horror', 'Ужасы'), ('mystery', 'Мистика'), ('drama', 'Драма'), ('comedy', 'Комедия'), ('biography', 'Биография'), ('philosophy', 'Философия'), ('psychology', 'Психология'), ('history', 'История'), ('science', 'Наука'), ('popular_science', 'Научно-популярная литература'), ('nonfiction', 'Нон-фикшн'), ('poetry', 'Поэзия'), ('children', 'Детская'), ('young_adult', 'Для подростков'), ('self_help', 'Саморазвитие'), ('comic', 'Комикс'), ('manga', 'Манга'), ('fanfiction', 'Фанфик'), ('erotica', 'Эротика'), ('novel', 'Роман'), ('other', 'Другое')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booksubmission',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Художественная литература'), ('classic', 'Классика'), ('fantasy', 'Фэнтези'), ('dystopia', 'Антиутопия'), ('scifi', 'Научная фантастика'), ('detective', 'Детектив'), ('thriller', 'Триллер'), ('romance', 'Любовный роман'), ('short_story', 'Рассказ'), ('novella', 'Повесть'), ('historical', 'Исторический'), ('adventure', 'Приключения'), ('horror', 'Ужасы'), ('mystery', 'Мистика'), ('drama', 'Драма'), ('comedy', 'Комедия'), ('biography', 'Биография'), ('philosophy', 'Философия'), ('psychology', 'Психология'), ('history', 'История'), ('science', 'Наука'), ('popular_science', 'Научно-популярная литература'), ('nonfiction', 'Нон-фикшн'), ('poetry', 'Поэзия'), ('children', 'Детская'), ('young_adult', 'Для подростков'), ('self_help', 'Саморазвитие'), ('comic', 'Комикс'), ('manga', 'Манга'), ('fanfiction', 'Фанфик'), ('erotica', 'Эротика'), ('novel', 'Роман'), ('other', 'Другое')], max_length=50, verbose_name='Жанр'),
        ),
        migrations.CreateModel(
            name='ReviewReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', '👍'), ('dislike', '👎')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='books.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('review', 'user')},
            },
        ),
    ]
