# Generated by Django 5.2.12 on 2026-04-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_review_reviewer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer_role',
            field=models.CharField(blank=True, choices=[('staff', 'Персонал клуба'), ('active', 'Активный читатель'), ('guest', 'Гость')], default='staff', max_length=20, verbose_name='Роль автора на момент оценки'),
        ),
    ]
