# Generated by Django 5.2.12 on 2026-04-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_review_reviewer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewer_role',
        ),
    ]
