# Generated by Django 6.0.1 on 2026-02-08 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название темы')),
                ('probability', models.FloatField(default=1.0, verbose_name='Вероятность (1-100)')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тема колеса',
                'verbose_name_plural': 'Темы колеса',
            },
        ),
        migrations.CreateModel(
            name='WheelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название конфигурации')),
                ('mode', models.CharField(choices=[('normal', 'Обычный'), ('elimination', 'Навыбывание'), ('battle_royale', 'Батлрояль')], default='normal', max_length=20)),
                ('sectors_count', models.IntegerField(default=12, verbose_name='Количество ячеек')),
                ('spin_duration', models.IntegerField(default=10, verbose_name='Время вращения (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Конфигурация колеса',
                'verbose_name_plural': 'Конфигурации колеса',
            },
        ),
        migrations.CreateModel(
            name='WheelSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.wheelconfiguration')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.wheeltheme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='wheelconfiguration',
            name='themes',
            field=models.ManyToManyField(through='games.WheelSector', to='games.wheeltheme'),
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_time', models.IntegerField(verbose_name='Время вращения')),
                ('spin_result', models.FloatField(verbose_name='Угол остановки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.wheelconfiguration')),
                ('winner_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.wheeltheme')),
            ],
            options={
                'verbose_name': 'История вращения',
                'verbose_name_plural': 'История вращений',
            },
        ),
    ]
