# Generated by Django 6.0.1 on 2026-02-08 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wheelconfiguration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wheeltheme',
            options={},
        ),
        migrations.RemoveField(
            model_name='wheelconfiguration',
            name='sectors_count',
        ),
        migrations.RemoveField(
            model_name='wheelconfiguration',
            name='themes',
        ),
        migrations.AlterField(
            model_name='wheelconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wheelconfiguration',
            name='name',
            field=models.CharField(default='Колесо фортуны', max_length=200, verbose_name='Название'),
        ),
    ]
