# Generated by Django 6.0.1 on 2026-02-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_wheelconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelconfiguration',
            name='elimination_round',
            field=models.IntegerField(default=0, verbose_name='Текущий раунд'),
        ),
        migrations.AddField(
            model_name='wheelconfiguration',
            name='is_elimination_active',
            field=models.BooleanField(default=False, verbose_name='Режим навыбывание'),
        ),
    ]
