# Generated by Django 6.0.1 on 2026-02-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_wheelconfiguration_elimination_round_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WheelSector',
        ),
    ]
