# Generated by Django 6.0.1 on 2026-02-08 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_add_user_fields_to_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spinhistory',
            options={'verbose_name': 'Старая история вращения', 'verbose_name_plural': 'Старая история вращений'},
        ),
        migrations.AlterModelOptions(
            name='wheeltheme',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='wheeltheme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='wheeltheme',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Глобальная тема для всех'),
        ),
        migrations.CreateModel(
            name='WheelSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Моя рулетка', max_length=200, verbose_name='Название')),
                ('mode', models.CharField(choices=[('normal', 'Обычный'), ('elimination', 'Навыбывание'), ('battle_royale', 'Батлрояль')], default='normal', max_length=20)),
                ('spin_duration', models.IntegerField(default=10, verbose_name='Время вращения (сек)')),
                ('is_elimination_active', models.BooleanField(default=False, verbose_name='Режим навыбывание')),
                ('elimination_round', models.IntegerField(default=0, verbose_name='Текущий раунд')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная сессия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия рулетки',
                'verbose_name_plural': 'Сессии рулетки',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserSpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_time', models.IntegerField(verbose_name='Время вращения')),
                ('spin_result', models.FloatField(verbose_name='Угол остановки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.wheeltheme')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.wheelsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'История вращения пользователя',
                'verbose_name_plural': 'История вращений пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна в сессии')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('probability', models.FloatField(default=1.0, verbose_name='Вероятность в сессии')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.wheeltheme')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.wheelsession')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'theme')},
            },
        ),
    ]
