# Generated by Django 6.0.1 on 2026-02-08 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_add_user_wheelsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspinhistory',
            name='session',
        ),
        migrations.RemoveField(
            model_name='userspinhistory',
            name='winner_theme',
        ),
        migrations.AlterUniqueTogether(
            name='wheelsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wheelsession',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='spinhistory',
            options={'verbose_name': 'История вращения', 'verbose_name_plural': 'История вращений'},
        ),
        migrations.AlterModelOptions(
            name='wheeltheme',
            options={},
        ),
        migrations.RemoveField(
            model_name='wheeltheme',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wheeltheme',
            name='is_global',
        ),
        migrations.AddField(
            model_name='wheelconfiguration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wheel_configurations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wheeltheme',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterUniqueTogether(
            name='wheelconfiguration',
            unique_together={('user', 'name')},
        ),
        migrations.CreateModel(
            name='WheelSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.wheelconfiguration')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.wheeltheme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='SessionTheme',
        ),
        migrations.DeleteModel(
            name='UserSpinHistory',
        ),
        migrations.DeleteModel(
            name='WheelSession',
        ),
    ]
