"""
Django settings for bookapp project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from easy_thumbnails.conf import Settings as thumbnail_settings

from django.conf.global_settings import AUTH_USER_MODEL, LOGIN_REDIRECT_URL, LOGOUT_REDIRECT_URL, EMAIL_BACKEND

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

load_dotenv() 

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


AUTH_USER_MODEL = 'users.User'
LOGIN_REDIRECT_URL = '/users/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/users/auth/login/'

# SECURE_SSL_REDIRECT = True

# Дополнительные настройки безопасности
SESSION_COOKIE_SECURE = True #Перехват сессии
CSRF_COOKIE_SECURE = True #CSRF-атаки
SECURE_BROWSER_XSS_FILTER = True #XSS-атаки
SECURE_CONTENT_TYPE_NOSNIFF = True #MIME-сниффинг
SECURE_HSTS_SECONDS = 0 #HTTP-подмена
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Если у вас Nginx за прокси
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'users',
    'books',
    'games',
    'easy_thumbnails',
    'image_cropping',
    'allauth',
    'allauth.account',
]

THUMBNAIL_ALIASES = {
    '': {
        'avatar': {
            'size': (300, 300),
            'crop': True,
            'upscale': True,
        },
        'avatar_small': {
            'size': (100, 100),
            'crop': True,
            'upscale': True,
        },
        'avatar_medium': {
            'size': (200, 200),
            'crop': True,
            'upscale': True,
        },
    },
}

THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumbnail_settings.THUMBNAIL_PROCESSORS

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  ###
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'core.middleware.RateLimitMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware'
]

ROOT_URLCONF = 'bookapp.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'books.context_processors.pending_submissions_count', ####
            ],
        },
    },
]

WSGI_APPLICATION = 'bookapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'ATOMIC_REQUESTS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 3  

# Отключаем стандартные URL-ы регистрации, оставляем только allauth
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'

# КРИТИЧЕСКИ ВАЖНЫЕ НАСТРОЙКИ для обязательного подтверждения
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 'mandatory' - обязательное подтверждение
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  # подтверждение по клику на ссылку
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False 
ACCOUNT_EMAIL_CONFIRMATION_HMAC = True  
ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN = 180  

ACCOUNT_SIGNUP_REDIRECT_URL = '/accounts/confirm-email/'
LOGIN_REDIRECT_URL = '/home/'

# Настройки логина
ACCOUNT_AUTHENTICATION_METHOD = 'email'  
ACCOUNT_USERNAME_REQUIRED = False  
ACCOUNT_FORMS = {
    'signup': 'users.forms.CustomSignupForm',  
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.timeweb.ru'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # или EMAIL_USE_SSL = True для порта 465
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
SERVER_EMAIL = os.getenv("SERVER_EMAIL")

# Redis настройки

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache'),
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Настройки кеширования страниц
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300  # 5 минут
CACHE_MIDDLEWARE_KEY_PREFIX = 'site_cache'


# REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
#
# # Кэширование (для django-redis)
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake',
#     }
# }
#
# CACHE_SETTINGS = {
#     'TOP_BOOKS_TIMEOUT': 300,  # 5 минут
#     'BOOK_DETAIL_TIMEOUT': 600,  # 10 минут
# }
#
# # Настройки лимитера
# RATE_LIMIT_CONFIG = {
#     'DEFAULT': {'requests': 30, 'window': 30},  # 60 запросов в минуту
#     'LIMITS': {
#         '/': {'requests': 10, 'window': 20},      # Главная: 20 за 10 сек
#         '/books/top/': {'requests': 10, 'window': 20},  # ТОП: 10 за 5 сек
#         '/books/submit/': {'requests': 5, 'window': 30},  # Предложка: 5 за 30 сек
#         # '/api/': {'requests': 30, 'window': 60},  # API: 30 в минуту
#         '/books/book/': {'requests': 10, 'window': 60},
#
#         # ДИНАМИЧЕСКИЙ ПУТЬ ДЛЯ РЕАКЦИЙ НА РЕЦЕНЗИИ
#         're:/books/review/[0-9]+/react/': {'requests': 10, 'window': 60},
#
#         # Другие динамические пути
#         're:/books/book/[0-9]+/favorite/': {'requests': 2, 'window': 30},
#         're:/books/book/[0-9]+/review/': {'requests': 10, 'window': 30},
#     },
#     'EXCLUDED_PATHS': [
#         '/health',
#         '/favicon.ico',
#         '/static/',
#         '/media/',
#         '/admin/',
#         '/robots.txt',
#         '/sitemap.xml',
#     ]
# }


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django.db.backends': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     },
# }

